### ISSUE TITLE
Bosh init VM create error

### ISSUE THREAD

**Issue by Prospecta** [cloudfoundry-incubator/bosh-vcloud-cpi-release#12]
Hi,

I am encountering an error when attempting to run the bosh-init deploy script on vCloud (not vCloud Air).

The job fails when attempting to create the vm:

--------------------

Command 'deploy' failed:
Deploying:
Creating instance 'bosh/0':
Creating VM:
Creating vm with stemcell cid 'urn:vcloud:catalogitem:decd3c65-5dde-47ae-836e-100199cdae0d':
CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Task urn:vcloud:task:14f18678-7d9a-4046-a1aa-d708c8058be0 Updated Virtual Machine 3b6b2f67-572c-44c4-74d4-a80b28887836(be1c153c-6e01-46b3-81c5-018ec2c26c10) completed unsuccessfully, Details: [ 01b88b27-f995-41dd-b39e-c2d498b808fb-3776 ] Unable to perform this action. Contact your cloud admi...","ok_to_retry":false}

--------------------

and vCloud returns the error:

--------------------

com.vmware.ssdc.library.exceptions.DatastoreNotAvailableException: null
at com.vmware.vcloud.fabric.storage.placement.sdrs.impl.SdrsPlacementManagerImpl.processSdrsResults(SdrsPlacementManagerImpl.java:1040)
at com.vmware.vcloud.fabric.storage.placement.sdrs.impl.SdrsPlacementManagerImpl.selectDatastoreInStoragePod(SdrsPlacementManagerImpl.java:213)
at com.vmware.vcloud.fabric.storage.placement.impl.VirtualMachineDiskLevelStorageSelectorImpl.selectDatastore(VirtualMachineDiskLevelStorageSelectorImpl.java:369)
at com.vmware.vcloud.fabric.storage.storedVm.impl.RelocateStoredVmByStorageClassActivity$CalculateTargetDatastorePhase.invoke(RelocateStoredVmByStorageClassActivity.java:138)
at com.vmware.vcloud.activity.executors.ActivityRunner.runPhase(ActivityRunner.java:156)
at com.vmware.vcloud.activity.executors.ActivityRunner.run(ActivityRunner.java:118)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

--------------------

The vClouderror reports that the datastore is not available when in fact there is a valid datastore available for the deployment which has no issues when creating a vm manually via vCloud Director. The stemcell is also uploaded to the datastore with no issues.

We had previously deployed Cloud Foundry v182 including Bosh with no trouble on vCloud but now struggle with the latest releases (bosh v257.9 & vCloud CPI v24). We have attempted to use both the latest vCloud and vSphere stemcells (v3262.12) with no luck.

For reference, below is the vcd section of the bosh.yml:

--------------------
vcd: &vcd # <--- Replace values below
  url: https://*******************
  user: **********
  password: ************
  entities:
    organization: Cloud-Foundry
    virtual_datacenter: Cloud-Foundry-VDC
    vapp_catalog: cf-catalog-bosh
    media_catalog: cf-catalog-bosh
    media_storage_profile: '*'
    vm_metadata_key: bosh-meta
  control: {wait_max: 900}

--------------------

Any ideas what could be causing the issue?

Thanks

**Comment by cunnie** [comment]
@Prospecta afraid we haven't seen that error before. You might try running `BOSH_INIT_LOG_LEVEL=debug BOSH_INIT_LOG_PATH=/tmp/bosh-debug.log bosh-init deploy your-manifest.yml` and attach the debug logs to this issue. Please scrub any passwords from these logs first as they may contain sensitive info.

**Comment by Prospecta** [comment]
Thanks Cunnie,

Please check the attached logs
[bosh.log.zip](https://github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release/files/471007/bosh.log.zip)

**Comment by cunnie** [comment]
Thanks @Prospecta,

Some things to try:
* Can you manually create and attach a hard disk to a manually created VM?
* Can you try this with a completely fresh deploy with a new vApp name and no existing VMs?
* If you're still stuck, you might have to open a support ticket with the vCloud folks. The debug logs contain every call the CPI made. If vCloud Support determines the CPI is making an incorrect call, we can continue investigating.

To speed up your debugging, you can deploy a VM with no jobs rather than an entire CF. Here's part of a manifest to accomplish this (we haven't tried this ourselves, but it should work):

```yaml
---
name: empty

releases:
- name: bosh-vcloud-cpi
   url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release?v=24
   sha1: 6b223f73f3818363b6af15a7326d3894ea0c56c6

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vcloud-esxi-ubuntu-trusty-go_agent?v=3262.12
    sha1: 333187bc7f7e35cd714c0aa8c4f699393cdcb0c2
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 20_000

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: 10.85.57.0/24
    gateway: 10.85.57.1
    dns: [8.8.8.8]
    cloud_properties: {name: VM Network} # <--- Replace with Network name

instance_groups:
- name: empty_vm
  instances: 1
  jobs: []
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - {name: private, static_ips: [10.0.0.6]}

cloud_provider:
  template: {name: vcloud_cpi, release: bosh-vcloud-cpi}
  mbus: "https://mbus:mbus-password@10.0.0.6:6868"
  properties:
    vcd:
      url: VCLOUD-URL
      user: VCLOUD-USER
      password: VCLOUD-PASSWORD
      entities:
        organization: VDC-ORGANIZATION
        virtual_datacenter: VDC-NAME
        vapp_catalog: bosh-catalog
        media_catalog: bosh-catalog
        media_storage_profile: '*'
        vm_metadata_key: bosh-meta
      control: {wait_max: 900}
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
...
```

Some notes:
* on line 14402, we see the first error: `Unable to perform this action. Contact your cloud administrator." minorErrorCode="INTERNAL_SERVER_ERROR"/>`. Typically when we see `INTERNAL_SERVER_ERROR`, it indicates that the CPI is working properly but the vCloud is unable to fulfill the request (something is broken)
* Prior to failing call, the CPI was able to successfully create a VM and set the VM's network config. However, the CPI automatically deletes the VM after the following failure
* tracing back, we see on line 13872, that the call which failed was `D, [2016-09-14T00:16:02.154698 #16903] DEBUG -- : STEP VCloudCloud::Steps::ReconfigureVM`
* the [`ReconfigureVM` step](https://github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release/blob/4c72d19009eb0c5378db08f230a8a018efded5ed/src/bosh_vcloud_cpi/lib/cloud/vcloud/steps/reconfigure_vm.rb) sets the CPU and RAM values for the VM, creates a hard disk, and attaches the NICs. Given your server-side stack trace mentions datastores, the hard disk call seems the most likely culprit.

— Lyle Franklin & Brian Cunnie
